import type { Village } from "../types/village.types";

export const VILLAGES: Village[] = [
  {
    name: "Jacobabad",
    province: "Sindh",
    district: "Jacobabad",
    lat: 28.2831,
    lon: 68.4416,
    population: 95000,
    baselineDischarge: 850,
    highRiskMonths: "July-September",
  },
  {
    name: "Dadu",
    province: "Sindh",
    district: "Dadu",
    lat: 27.7808,
    lon: 67.7771,
    population: 120000,
    baselineDischarge: 920,
    highRiskMonths: "July-September",
  },
  {
    name: "Kashmore",
    province: "Sindh",
    district: "Kashmore",
    lat: 27.6206,
    lon: 68.0372,
    population: 85000,
    baselineDischarge: 880,
    highRiskMonths: "July-September",
  },
  {
    name: "Larkana",
    province: "Sindh",
    district: "Larkana",
    lat: 27.5614,
    lon: 68.2048,
    population: 110000,
    baselineDischarge: 900,
    highRiskMonths: "July-September",
  },
  {
    name: "Rajanpur",
    province: "Punjab",
    district: "Rajanpur",
    lat: 28.4286,
    lon: 70.3122,
    population: 75000,
    baselineDischarge: 950,
    highRiskMonths: "July-September",
  },
  {
    name: "Dera Ghazi Khan",
    province: "Punjab",
    district: "D.G. Khan",
    lat: 29.9607,
    lon: 70.6308,
    population: 140000,
    baselineDischarge: 1100,
    highRiskMonths: "July-September",
  },
  {
    name: "Sargodha",
    province: "Punjab",
    district: "Sargodha",
    lat: 32.0856,
    lon: 72.6377,
    population: 500000,
    baselineDischarge: 2200,
    highRiskMonths: "July-September",
  },
  {
    name: "Khanewal",
    province: "Punjab",
    district: "Khanewal",
    lat: 30.192,
    lon: 71.9435,
    population: 620000,
    baselineDischarge: 2100,
    highRiskMonths: "July-September",
  },
  {
    name: "Bahawalpur",
    province: "Punjab",
    district: "Bahawalpur",
    lat: 29.3956,
    lon: 71.6858,
    population: 200000,
    baselineDischarge: 1800,
    highRiskMonths: "July-September",
  },
  {
    name: "Sukkur",
    province: "Sindh",
    district: "Sukkur",
    lat: 27.7065,
    lon: 68.8739,
    population: 480000,
    baselineDischarge: 2400,
    highRiskMonths: "July-September",
  },
  {
    name: "Mehar",
    province: "Sindh",
    district: "Dadu",
    lat: 27.6,
    lon: 67.65,
    population: 45000,
    baselineDischarge: 750,
    highRiskMonths: "July-September",
  },
  {
    name: "Jhang",
    province: "Punjab",
    district: "Jhang",
    lat: 31.2743,
    lon: 72.3147,
    population: 680000,
    baselineDischarge: 2300,
    highRiskMonths: "July-September",
  },
  {
    name: "Multan",
    province: "Punjab",
    district: "Multan",
    lat: 30.1575,
    lon: 71.4454,
    population: 1800000,
    baselineDischarge: 2600,
    highRiskMonths: "July-September",
  },
  {
    name: "Ghotki",
    province: "Sindh",
    district: "Ghotki",
    lat: 27.8253,
    lon: 68.7619,
    population: 70000,
    baselineDischarge: 820,
    highRiskMonths: "July-September",
  },
  {
    name: "Sanghar",
    province: "Sindh",
    district: "Sanghar",
    lat: 27.0906,
    lon: 68.9552,
    population: 65000,
    baselineDischarge: 700,
    highRiskMonths: "July-September",
  },
  {
    name: "Naushahro Feroze",
    province: "Sindh",
    district: "Naushahro Feroze",
    lat: 27.2523,
    lon: 68.4122,
    population: 120000,
    baselineDischarge: 780,
    highRiskMonths: "July-September",
  },
  {
    name: "Mithi",
    province: "Sindh",
    district: "Tharparkar",
    lat: 24.7421,
    lon: 70.1879,
    population: 35000,
    baselineDischarge: 200,
    highRiskMonths: "July-September",
  },
  {
    name: "Mingora",
    province: "Khyber Pakhtunkhwa",
    district: "Swat",
    lat: 34.7679,
    lon: 72.4464,
    population: 380000,
    baselineDischarge: 800,
    highRiskMonths: "June-August",
  },
];
